apiVersion: v1
kind: Secret
metadata:
  name: clinops-config
  namespace: clinops
stringData:
  DATABASE_URL: postgresql://postgres:postgres@postgres.postgres.svc:5432/clinops?schema=public
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://tempo.observability.svc:4318/v1/traces
  OTEL_SERVICE_NAME: clinops-app
  JWT_SECRET: ${JWT_SECRET}
